DROP TABLE BGGBP001.TBE005_DOWN CASCADE CONSTRAINTS;

CREATE TABLE BGGBP001.TBE005_DOWN
(
  CD_ENTIDAD   NUMBER,
  CD_NIVEL1    NUMBER,
  CD_NIVEL2    NUMBER,
  TP_SERVICIO  NUMBER,
  FECHA        VARCHAR2(10 BYTE),
  CD_MONEDA    VARCHAR2(2 BYTE),
  STD          VARCHAR2(1 BYTE)
)
TABLESPACE EGGR001_TRANSACTION
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
